package com.gkm.rickmorty.ui.theme

import androidx.compose.ui.graphics.Color

/*---------------------Light Color----------------------*/
val primaryLight = Color(0xFF48672F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC9EEA7)
val onPrimaryContainerLight = Color(0xFF0C2000)
val secondaryLight = Color(0xFF56624B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDAE7C9)
val onSecondaryContainerLight = Color(0xFF141E0C)
val tertiaryLight = Color(0xFF386665)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBBECEA)
val onTertiaryContainerLight = Color(0xFF00201F)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF9FAEF)
val onBackgroundLight = Color(0xFF1A1D16)
val surfaceLight = Color(0xFFF9FAEF)
val onSurfaceLight = Color(0xFF1A1D16)
val surfaceVariantLight = Color(0xFFE0E4D6)
val onSurfaceVariantLight = Color(0xFF44483E)
val outlineLight = Color(0xFF74796D)
val outlineVariantLight = Color(0xFFC4C8BA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E312A)
val inverseOnSurfaceLight = Color(0xFFF0F2E7)
val inversePrimaryLight = Color(0xFFADD28E)
val surfaceDimLight = Color(0xFFD9DBD0)
val surfaceBrightLight = Color(0xFFF9FAEF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F5EA)
val surfaceContainerLight = Color(0xFFEDEFE4)
val surfaceContainerHighLight = Color(0xFFE7E9DE)
val surfaceContainerHighestLight = Color(0xFFE2E3D9)

/*------------Dark Color-----------------*/
val primaryDark = Color(0xFFADD28E)
val onPrimaryDark = Color(0xFF1B3704)
val primaryContainerDark = Color(0xFF314E19)
val onPrimaryContainerDark = Color(0xFFC9EEA7)
val secondaryDark = Color(0xFFBECBAE)
val onSecondaryDark = Color(0xFF29341F)
val secondaryContainerDark = Color(0xFF3F4A34)
val onSecondaryContainerDark = Color(0xFFDAE7C9)
val tertiaryDark = Color(0xFFA0CFCE)
val onTertiaryDark = Color(0xFF003736)
val tertiaryContainerDark = Color(0xFF1E4E4D)
val onTertiaryContainerDark = Color(0xFFBBECEA)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF11140E)
val onBackgroundDark = Color(0xFFE2E3D9)
val surfaceDark = Color(0xFF11140E)
val onSurfaceDark = Color(0xFFE2E3D9)
val surfaceVariantDark = Color(0xFF44483E)
val onSurfaceVariantDark = Color(0xFFC4C8BA)
val outlineDark = Color(0xFF8E9286)
val outlineVariantDark = Color(0xFF44483E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E3D9)
val inverseOnSurfaceDark = Color(0xFF2E312A)
val inversePrimaryDark = Color(0xFF48672F)
val surfaceDimDark = Color(0xFF11140E)
val surfaceBrightDark = Color(0xFF373A33)
val surfaceContainerLowestDark = Color(0xFF0C0F09)
val surfaceContainerLowDark = Color(0xFF1A1D16)
val surfaceContainerDark = Color(0xFF1E211A)
val surfaceContainerHighDark = Color(0xFF282B24)
val surfaceContainerHighestDark = Color(0xFF33362F)
